# ========================================================================
# ======                      INGESTION SETTINGS                    ======
# ========================================================================
ingestion:
    path_root_datasets: "data/in/Pratik_datalake"
    
    xarray_load_settings:
        chunks: auto
    
    filename_components:
        temperature_dataset: 
            #prefix: "dataset_temperature_dummy"
            prefix: "ERA5land_global_t2m_daily_0.5_"
            suffix: 
            extension: ".nc"
        rainfall_dataset: 
            #prefix: "dataset_rainfall_dummy"
            prefix: "ERA5land_global_tp_daily_0.5_"
            suffix: 
            extension: ".nc"
        human_population_dataset: 
            #prefix: "dataset_population_dummy"
            prefix: "pop_dens_"
            #suffix: 
            suffix: "_global_0.5"
            extension: ".nc"

    initial_conditions:
        file_path_initial_conditions:


# ========================================================================
# ======                   TRANSFORMATION SETTINGS                  ======
# ========================================================================
transformation:
    # # ---- Temperature Data
    temperature_dataset:
        #data_variable : "temperature"
        data_variable: "t2m"
        preprocessing:
            names_dimensions: 
                #"time": "time"
                "valid_time": "time"
            dimension_order: 
                - "longitude"
                - "latitude"
                - "time"
        
    # # ---- Rainfall Data
    rainfall_dataset:
        #data_variable : "rainfall"
        data_variable: "tp"
        preprocessing:
            dimension_order: 
                - "longitude"
                - "latitude"
                - "time"
    
    # # ---- Human population Data
    human_population_dataset:
        #data_variable : "population"
        data_variable: "dens"
        preprocessing:
            names_dimensions: 
                #"longitude": "longitude"
                "lon": "longitude"
                #"latitude": "latitude"
                "lat": "latitude"
            dimension_order: 
                - "longitude"
                - "latitude"
                - "time"
        postprocessing:
            align_dataset: True


# =================================================================
# ======                   SERVING SETTINGS                  ======
# =================================================================
serving: 
    path_output_datasets: "data/in/Pratik_datalake"
    filename_components:
        prefix: "Mosquito_abundance_Global_"
        suffix: 
        extension: ".nc"

# =================================================================
# ======                  ODE SYSTEM SETTINGS                ======
# =================================================================
ode_system:
    time_step: 10
    model_variables:
        - "eggs"
        - "ed"
        - "juv"
        - "imm"
        - "adults"
